name: Verify code (lint, test, typecheck)

on:
  pull_request:
    branches: [ main ]

jobs:
  verify:
    name: Verify (lint, test, typecheck)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Enable pnpm (Corepack)
        run: |
            corepack enable
            corepack prepare pnpm@latest --activate
            npm install -g pnpm@latest
            pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: test-web
        run: pnpm test:web

      - name: test-worker
        run: pnpm test:worker
